import {
  BarChartOutline,
  BookOutline,
  DashboardOutline,
  FilterOutline,
  FormOutline,
  GlobalOutline,
  LeftOutline,
  LoginOutline,
  LogoutOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  RightOutline,
  SearchOutline,
  SettingOutline,
  SkinOutline,
  WalletOutline,
  WarningFill,
} from '@ant-design/icons-angular/icons';

export const nzIcons = [
  BarChartOutline,
  BookOutline,
  DashboardOutline,
  FilterOutline,
  FormOutline,
  GlobalOutline,
  LeftOutline,
  LoginOutline,
  LogoutOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  RightOutline,
  SearchOutline,
  SettingOutline,
  SkinOutline,
  WalletOutline,
  WarningFill,
];
